 # Makefile
 # Riesenie ISA-Nastroj monitorovanie RIP a RIPng, 15.11.2015
 # Autor Dusan Zeliar,xzelia00, FIT
 # Přeloženo g++ 4.8.4

all: myripsniffer myripresponse
#compile 
myripsniffer:
	g++ myripsniffer.cpp -lpcap -o myripsniffer
myripresponse:
	g++ myripresponse.cpp -w -o myripresponse
